config/routes.rb
InstagramClone::Application.routes.draw do
  devise_for :users
  root 'post#index'
  resources :tags, only: [:show]

  resources :posts do
    resources :comments
    resources :votes
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" },
    storage: :s3,
    bucket: 'instagram-clone',
    s3_credentials: {
      access_key_id: Rails.application.secrets.s3_access_key,
      secret_access_key: Rails.application.secrets.s3_secret_key
    }

   	validates :description, presence: true
   	validates_attachment_content_type :picture, content_type: ["image/jpg", "image/jpeg", "image/png"]

   	has_many :votes
    has_and_belongs_to_many :tags
    has_many :comments
    belongs_to :user

    # geocoded_by :address
    # after_validation :geocode
    # after_save
    # before_save
    # after_create
    # after_update

	def tag_names
		tags.map(&:name).join
	end

	def tag_names=(tag_names)
		tag_names.split(' ').uniq.each do |tag_name|
			tag = Tag.find_or_create_by(name: tag_name)
			tags << tag
		end
	end

  def vote_count
    votes.up.count - votes.down.count
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_and_belongs_to_many :posts

	def to_param
		name.delete('#')
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :post
  enum direction: [:up, :down]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def new
		@post = Post.find params[:post_id]
		@comment = Comment.new
	end

	def create
		@post = Post.find params[:post_id]
		@post.comments.new params[:comment].permit(:content)

		if @post.save
			flash[:notice] = 'Thanks for your comment'
			redirect_to '/posts'
		else
			render 'new'
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new params[:post].permit(:description, :picture, :tag_names)

    if @post.save
      redirect_to '/posts'
    else
      render 'new'
    end
  end

  def destroy
    @post = Post.find params[:id]
    @post.destroy

    flash[:notice] = 'Post successfully deleted.'

    redirect_to '/posts'
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def show
		@tag = Tag.find_by(name: '#' + params[:id])
	end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
	def create
		@post = Post.find params[:post_id]

		@post.votes.create direction: params[:direction]
		redirect_to '/posts'
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/new.html.erb
<%= form_for [@post, @comment] do |f| %>
  <%= f.label :content, 'Comment' %>
  <%= f.text_area :content %>

  <%= f.submit %>
<% end %>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InstagramClone</title>
<!--   <link href="css/bootstrap.min.css" rel="stylesheet"> -->

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
     <div id="left"> 
	   	<div id="slides">
	   	  <p><%= link_to 'Home', '/posts', class: 'btn btn-primary' %>
     		<%= link_to 'New Post', '/posts/new', class: 'btn btn-primary' %></p>  
     			    </div> 
	      	<div class="slides_container center">
	      		<p>Instagran<img src="http://www.yoda.arachsys.com/worms/wa/anims/extramaps/oldwoman.gif" class="heading"></p>
	      	</div>           
	  </div>
	</header>
	<%= yield %>
</body>
</html>

app/views/posts/_post.html.erb
  <div class="row">
	  	<div class="col-md-4">
	  		<%= image_tag post.picture.url(:medium), class: 'uploaded-pic, img-rounded'%>
	  		<p><%= post.description %>
	  			<%= post.tags.each do |tag| %>
	  				<%= link_to tag.name, tag %>
	  			<% end %>
	  		</p>
	  		<p><%= link_to 'Delete', post_path(post), method: :delete, class: 'btn btn-danger' %>
	  			<%= link_to 'Add a comment', new_post_comment_path(post), class: 'btn btn-primary' %>

	  		</p>
	  	</div>
  </div>

app/views/posts/index.html.erb
  <div class='row'>
  <% if @posts.any? %>
    <% @posts.each do |post| %>
      <div class="col-md-4">
        <div class="thumbnail">
          <%= image_tag post.picture.url(:medium), class: 'img-rounded' %>
          <div class="caption">
            <h3><%= post.description %></h3>
            <p>
              <% post.tags.each do |tag| %>
                <%= link_to tag.name, tag %>
              <% end %>
            </p>
            <%= post.comments.count %> comments
              <p><%= button_to 'Upvote', post_votes_path(post, direction: :up) %> <%= button_to 'Downvote', post_votes_path(post, direction: :down) %></p><h3 class='votes_count'><%= post.vote_count %></h3><p><%= link_to 'Delete', post_path(post), method: :delete, class: 'btn btn-danger' %>
               <%= link_to 'Add a comment', new_post_comment_path(post), class: 'btn btn-primary' %>
               </p>
           </div>
         </div>
       </div>
     <% end %>
   <% else %>
     No posts yet
 <% end %>
 </div>

app/views/posts/new.html.erb
<% if @post.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

		<ul>
		<% @post.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

<%= form_for @post, html: { multipart: true } do |f| %>
	<%= f.label :description %>
	<%= f.text_area :description %>

	<%= f.label :tag_names, 'Tags' %>
	<%= f.text_field :tag_names %>

	<%= f.label :picture %>
	<%= f.file_field :picture %>

	<%= f.submit %>
<% end %>

app/views/tags/show.html.erb
<%= render @tag.posts %>